# Generated by Django 4.2.5 on 2023-10-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_a_set",
                to="scorings.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_b_set",
                to="scorings.team",
            ),
        ),
    ]
