# Generated by Django 4.2.5 on 2023-10-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorings", "0002_alter_match_team_a_alter_match_team_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
